# -*- coding: utf-8 -*-
"""Translator Hugging Face

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mX24y2KK-N6YmeoPccUbcEOh1f1-c5Aj
"""

!pip install transformers
!pip install torch

from transformers import pipeline
import torch

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("translation", model="facebook/nllb-200-distilled-600M")

text = """\
My puppy is adorable, \
Your kitten is cute.
Her panda is friendly.
His llama is thoughtful. \
We all have nice pets!"""

text_translated = pipe(text,
                             src_lang="eng_Latn",
                             tgt_lang="fra_Latn")

text_translated